services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  api.instance1:
    image: ${DOCKER_REGISTRY-}apigrrinnovationsreverseproxyloadbalancer.api
    build:
      context: .
      dockerfile: Api.GRRInnovations.ReverseProxy.Loadbalancer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - InstanceName=API_1
    ports:
      - "5001:80"
    depends_on:
      - redis
  api.instance2:
    image: ${DOCKER_REGISTRY-}apigrrinnovationsreverseproxyloadbalancer.api
    build:
      context: .
      dockerfile: Api.GRRInnovations.ReverseProxy.Loadbalancer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - InstanceName=API_2
    ports:
      - "5002:80"
    depends_on:
      - redis
  reverseproxy.gateway:
    image: ${DOCKER_REGISTRY-}apigrrinnovationsreverseproxyloadbalancer.gateway
    build:
      context: .
      dockerfile: Api.GRRInnovations.ReverseProxy.Loadbalancer.Gateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    depends_on:
      - api.instance1
      - api.instance2